SHOW databases;
CREATE database comex_brasil_db;
DROP DATABASE comex_brasil_db;
USE comex_brasil_db;

DROP TABLE IMP;
DROP TABLE EXP;

CREATE TABLE EXP (
    ID_EXP BIGINT PRIMARY KEY AUTO_INCREMENT,
    CO_ANO VARCHAR(4) NOT NULL,
    CO_MES VARCHAR(2) NOT NULL,
    KG_LIQUIDO VARCHAR(50),
    VL_FOB VARCHAR(50),
    VL_AGREGADO VARCHAR(50),
    NO_PAIS VARCHAR(50),
    NO_VIA VARCHAR(50),
    SG_UF VARCHAR(50),
    NO_UF VARCHAR(50),
    NO_REGIAO VARCHAR(50),
    NO_URF VARCHAR(50),
    CO_FAT_AGREG VARCHAR(50),
    NO_SH6_POR VARCHAR(50),
    NO_SH4_POR VARCHAR(50),
    NO_SH2_POR VARCHAR(50)
);

CREATE TABLE IMP (
    ID_IMP BIGINT PRIMARY KEY AUTO_INCREMENT,
    CO_ANO VARCHAR(4) NOT NULL,
    CO_MES VARCHAR(2) NOT NULL,
    KG_LIQUIDO VARCHAR(50),
    VL_FRETE VARCHAR(50), 
    VL_SEGURO VARCHAR(50),
    VL_FOB VARCHAR(50),
    NO_PAIS VARCHAR(50),
    NO_VIA VARCHAR(50),
    SG_UF VARCHAR(50),
    NO_UF VARCHAR(50),
    NO_REGIAO VARCHAR(50),
    NO_URF VARCHAR(50),
    NO_SH6_POR VARCHAR(50),
    NO_SH4_POR VARCHAR(50),
    NO_SH2_POR VARCHAR(50)
);

SET GLOBAL local_infile = 1;
SET GLOBAL net_buffer_length = 33554432;


SHOW VARIABLES LIKE 'local_infile';
SHOW VARIABLES LIKE 'interactive_timeout';
SHOW VARIABLES LIKE 'net_read_timeout';
SHOW VARIABLES LIKE 'net_write_timeout';
SHOW VARIABLES LIKE 'wait_timeout';
SHOW VARIABLES LIKE 'max_allowed_packet';
SHOW VARIABLES LIKE 'innodb_buffer_pool_size';

/*Serve pra implementar o arquivo CSV nas tabelas*/
-- LOAD DATA LOCAL INFILE '/Users/user_name/Desktop/exp_tratado_2025-2014.csv' 
LOAD DATA LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\exp_tratado_2025-2014.csv'
INTO TABLE EXP
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CO_ANO,CO_MES,KG_LIQUIDO,VL_FOB,VL_AGREGADO,NO_PAIS,NO_VIA,SG_UF,NO_UF,NO_REGIAO,NO_URF,CO_FAT_AGREG,NO_SH6_POR,NO_SH4_POR,NO_SH2_POR);

LOAD DATA LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\imp_tratado_2025-2014.csv'
INTO TABLE IMP
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CO_ANO,CO_MES,KG_LIQUIDO,VL_FRETE,VL_SEGURO,VL_FOB,VL_AGREGADO,NO_PAIS,NO_VIA,SG_UF,NO_UF,NO_REGIAO,NO_URF,CO_FAT_AGREG,NO_SH6_POR,NO_SH4_POR,NO_SH2_POR);

-- CREATE INDEX 
CREATE INDEX sh6_idx ON COMEX_EXP (NO_SH6_POR);
CREATE INDEX sh4_idx ON COMEX_EXP (NO_SH4_POR);
CREATE INDEX sh2_idx ON COMEX_EXP (NO_SH2_POR);

SELECT COUNT(CO_ANO) AS NumerosDeAnos FROM EXP;
SELECT COUNT(CO_ANO) AS NumerosDeAnos FROM IMP;
SELECT * FROM EXP;
SELECT * FROM IMP;



