--|    mysql --local-infile=1 -u root -p 

CREATE DATABASE PONTOLOG;
USE PONTOLOG;

CREATE TABLE EXPORTACAO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CO_ANO INT,
    CO_MES TINYINT,
    KG_LIQUIDO DECIMAL(15,3),
    VL_FOB DECIMAL(15,2),
    VL_AGREGADO DECIMAL(15,2),
    NO_PAIS VARCHAR(50),
    NO_VIA VARCHAR(50),
    SG_UF CHAR(2),
    NO_UF VARCHAR(150),
    NO_REGIAO VARCHAR(30),
    NO_URF VARCHAR(150),
    CO_FAT_AGREG DECIMAL(5,1),
    NO_SH6_POR VARCHAR(400),
    NO_SH4_POR VARCHAR(255),
    NO_SH2_POR VARCHAR(255)
);

CREATE TABLE IMPORTACAO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CO_ANO INT,
    CO_MES TINYINT,
    KG_LIQUIDO DECIMAL(15,3),
    VL_TOTAL DECIMAL(15,2),
    VL_AGREGADO DECIMAL(15,2),
    NO_PAIS VARCHAR(50),
    NO_VIA VARCHAR(50),
    SG_UF CHAR(2),
    NO_UF VARCHAR(150),
    NO_REGIAO VARCHAR(30),
    NO_URF VARCHAR(150),
    CO_FAT_AGREG DECIMAL(5,1),
    NO_SH6_POR VARCHAR(400),
    NO_SH4_POR VARCHAR(255),
    NO_SH2_POR VARCHAR(255)
);

CREATE TABLE BALANCO_COMERCIAL(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CO_ANO varchar(4),
    CO_MES varchar(4),
    SG_UF varchar(5),
    BALANCA_COMERCIAL DECIMAL(50)
);

CREATE TABLE EXPORTACAO_RES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CO_ANO INT NOT NULL,
  SG_UF VARCHAR(2) DEFAULT NULL,
  NO_UF VARCHAR(255) DEFAULT NULL,
  NO_REGIAO VARCHAR(100) DEFAULT NULL,
  VL_AGREGADO DECIMAL(20,2) DEFAULT NULL,
  VL_FOB DECIMAL(20,2) DEFAULT NULL,
  KG_LIQUIDO DECIMAL(20,3) DEFAULT NULL,
  CO_FAT_AGREG DECIMAL(5,2) DEFAULT NULL,
  NO_VIA VARCHAR(100) DEFAULT NULL,
  NO_URF VARCHAR(255) DEFAULT NULL,
  NO_PAIS VARCHAR(200) DEFAULT NULL,
  NO_SH6_POR VARCHAR(450) DEFAULT NULL,
  NO_SH4_POR VARCHAR(255) DEFAULT NULL,
  NO_SH2_POR VARCHAR(255) DEFAULT NULL,
  QTD_REGISTROS INT DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IMPORTACAO_RES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CO_ANO INT NOT NULL,
  SG_UF VARCHAR(2) DEFAULT NULL,
  NO_UF VARCHAR(255) DEFAULT NULL,
  NO_REGIAO VARCHAR(100) DEFAULT NULL,
  VL_AGREGADO DECIMAL(20,2) DEFAULT NULL,
  VL_TOTAL DECIMAL(20,2),
  KG_LIQUIDO DECIMAL(20,3) DEFAULT NULL,
  CO_FAT_AGREG DECIMAL(5,2) DEFAULT NULL,
  NO_VIA VARCHAR(100) DEFAULT NULL,
  NO_URF VARCHAR(255) DEFAULT NULL,
  NO_PAIS VARCHAR(150) DEFAULT NULL,
  NO_SH6_POR VARCHAR(450) DEFAULT NULL,
  NO_SH4_POR VARCHAR(255) DEFAULT NULL,
  NO_SH2_POR VARCHAR(255) DEFAULT NULL,
  QTD_REGISTROS INT DEFAULT 0,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-------------------------------------------------------------------

SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE '../exp_tratado_2025-2014.csv'
INTO TABLE EXPORTACAO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CO_ANO, CO_MES, KG_LIQUIDO, VL_FOB, VL_AGREGADO, NO_PAIS, NO_VIA, SG_UF, NO_UF, 
 NO_REGIAO, NO_URF, CO_FAT_AGREG, NO_SH6_POR, NO_SH4_POR, NO_SH2_POR);

LOAD DATA LOCAL INFILE '/home/ubuntu/imp_tratado_2025-2014.csv'
INTO TABLE IMPORTACAO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CO_ANO, CO_MES, KG_LIQUIDO, VL_TOTAL, VL_AGREGADO, NO_PAIS, NO_VIA, SG_UF, NO_UF, 
 NO_REGIAO, NO_URF, CO_FAT_AGREG, NO_SH6_POR, NO_SH4_POR, NO_SH2_POR);

LOAD DATA LOCAL INFILE '/home/ubuntu/balanca_comercial_uf.csv'
INTO TABLE BALANCO_COMERCIAL
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CO_ANO, CO_MES, SG_UF, BALANCA_COMERCIAL);

------------------------------------------------------------------

INSERT INTO EXPORTACAO_RES (
  CO_ANO, SG_UF, NO_UF, NO_REGIAO,
  VL_AGREGADO, VL_FOB, KG_LIQUIDO,
  CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
  NO_SH6_POR, NO_SH4_POR, NO_SH2_POR,
  QTD_REGISTROS
)
SELECT 
  CO_ANO, SG_UF, NO_UF, NO_REGIAO,
  SUM(VL_AGREGADO), SUM(VL_FOB), SUM(KG_LIQUIDO),
  CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
  NO_SH6_POR, NO_SH4_POR, NO_SH2_POR,
  COUNT(*) AS QTD_REGISTROS
FROM EXPORTACAO
GROUP BY CO_ANO, SG_UF, NO_UF, NO_REGIAO,
         CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
         NO_SH6_POR, NO_SH4_POR, NO_SH2_POR
ORDER BY CO_ANO, SG_UF; 


INSERT INTO IMPORTACAO_RES (
  CO_ANO, SG_UF, NO_UF, NO_REGIAO,
  VL_AGREGADO, VL_TOTAL, KG_LIQUIDO,
  CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
  NO_SH6_POR, NO_SH4_POR, NO_SH2_POR,
  QTD_REGISTROS
)
SELECT 
  CO_ANO, SG_UF, NO_UF, NO_REGIAO,
  SUM(VL_AGREGADO), SUM(VL_TOTAL), SUM(KG_LIQUIDO),
  CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
  NO_SH6_POR, NO_SH4_POR, NO_SH2_POR,
  COUNT(*) AS QTD_REGISTROS
FROM IMPORTACAO
GROUP BY CO_ANO, SG_UF, NO_UF, NO_REGIAO,
         CO_FAT_AGREG, NO_VIA, NO_URF, NO_PAIS,
         NO_SH6_POR, NO_SH4_POR, NO_SH2_POR
ORDER BY CO_ANO, SG_UF;




------------------------------------------------------------

CREATE INDEX idx_ano_via               ON EXPORTACAO (CO_ANO, NO_VIA);
CREATE INDEX idx_ano_vl_fob_produto    ON EXPORTACAO (CO_ANO, VL_FOB, NO_SH6_POR);
CREATE INDEX idx_ano_fat_agreg         ON EXPORTACAO (CO_ANO, CO_FAT_AGREG);
CREATE INDEX idx_ano_no_sh6_por        ON EXPORTACAO (CO_ANO, NO_SH6_POR);
CREATE INDEX idx_ano_no_sh4_por        ON EXPORTACAO (CO_ANO, NO_SH4_POR);
CREATE INDEX idx_ano_urf               ON EXPORTACAO (CO_ANO, NO_URF);
CREATE INDEX idx_ano_mes_vl_agregado   ON EXPORTACAO (CO_ANO, CO_MES, VL_AGREGADO);
CREATE INDEX idx_ano_mes_kg_liquido    ON EXPORTACAO (CO_ANO, CO_MES, KG_LIQUIDO);
CREATE INDEX idx_ano_mes_vl_fob        ON EXPORTACAO (CO_ANO, CO_MES, VL_FOB);
CREATE INDEX idx_ano_vl_agregado       ON EXPORTACAO (CO_ANO, VL_AGREGADO);
CREATE INDEX idx_ano_kg_liquido        ON EXPORTACAO (CO_ANO, KG_LIQUIDO);
CREATE INDEX idx_ano_vl_fob            ON EXPORTACAO (CO_ANO, VL_FOB);
CREATE INDEX idx_no_sh6_por            ON EXPORTACAO (NO_SH6_POR);
CREATE INDEX idx_no_sh4_por            ON EXPORTACAO (NO_SH4_POR);
CREATE INDEX idx_no_sh2_por            ON EXPORTACAO (NO_SH2_POR);
CREATE INDEX idx_ano_uf                ON EXPORTACAO (SG_UF, CO_ANO);
CREATE INDEX idx_ano_pais              ON EXPORTACAO (CO_ANO,NO_PAIS,VL_FOB,VL_AGREGADO,KG_LIQUIDO);
CREATE INDEX idx_exportacao_completo   ON EXPORTACAO (CO_ANO,NO_REGIAO,CO_MES,VL_AGREGADO,KG_LIQUIDO,VL_FOB);
CREATE INDEX idx_region                ON EXPORTACAO (NO_REGIAO);


CREATE INDEX idx_ano_via               ON IMPORTACAO (CO_ANO, NO_VIA);
CREATE INDEX idx_ano_vl_total_produto  ON IMPORTACAO (CO_ANO, VL_TOTAL, NO_SH6_POR);
CREATE INDEX idx_ano_fat_agreg         ON IMPORTACAO (CO_ANO, CO_FAT_AGREG);
CREATE INDEX idx_ano_no_sh6_por        ON IMPORTACAO (CO_ANO, NO_SH6_POR);
CREATE INDEX idx_ano_no_sh4_por        ON IMPORTACAO (CO_ANO, NO_SH4_POR);
CREATE INDEX idx_ano_urf               ON IMPORTACAO (CO_ANO, NO_URF);
CREATE INDEX idx_ano_mes_vl_agregado   ON IMPORTACAO (CO_ANO, CO_MES, VL_AGREGADO);
CREATE INDEX idx_ano_mes_kg_liquido    ON IMPORTACAO (CO_ANO, CO_MES, KG_LIQUIDO);
CREATE INDEX idx_ano_mes_vl_total      ON IMPORTACAO (CO_ANO, CO_MES, VL_TOTAL);
CREATE INDEX idx_ano_vl_agregado       ON IMPORTACAO (CO_ANO, VL_AGREGADO);
CREATE INDEX idx_ano_kg_liquido        ON IMPORTACAO (CO_ANO, KG_LIQUIDO);
CREATE INDEX idx_ano_vl_total          ON IMPORTACAO (CO_ANO, VL_TOTAL);
CREATE INDEX idx_no_sh6_por            ON IMPORTACAO (NO_SH6_POR);
CREATE INDEX idx_no_sh4_por            ON IMPORTACAO (NO_SH4_POR);
CREATE INDEX idx_no_sh2_por            ON IMPORTACAO (NO_SH2_POR);
CREATE INDEX idx_ano_uf                ON IMPORTACAO (SG_UF, CO_ANO);
CREATE INDEX idx_ano_pais              ON IMPORTACAO (CO_ANO,NO_PAIS,VL_TOTAL,VL_AGREGADO,KG_LIQUIDO);
CREATE INDEX idx_importacao_region     ON IMPORTACAO (CO_ANO,NO_REGIAO,CO_MES,VL_AGREGADO,KG_LIQUIDO,VL_TOTAL);
CREATE INDEX idx_region                ON IMPORTACAO (NO_REGIAO);


CREATE INDEX idx_no_sh4_por	           ON EXPORTACAO_RES (NO_SH4_POR);
CREATE INDEX idx_no_sh6_por	           ON EXPORTACAO_RES (NO_SH6_POR);
CREATE INDEX idx_ano_co_fat_qtd        ON EXPORTACAO_RES (CO_ANO, CO_FAT_AGREG, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_co_fat_qtd     ON EXPORTACAO_RES (CO_ANO, SG_UF, CO_FAT_AGREG, QTD_REGISTROS);
CREATE INDEX idx_ano_no_sh4_por_qtd    ON EXPORTACAO_RES (CO_ANO, NO_SH4_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_no_sh6_por_qtd    ON EXPORTACAO_RES (CO_ANO, NO_SH6_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_no_sh4_por_qtd ON EXPORTACAO_RES (CO_ANO, SG_UF, NO_SH4_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_no_sh6_por_qtd ON EXPORTACAO_RES (CO_ANO, SG_UF, NO_SH6_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_urf_qtd 	       ON EXPORTACAO_RES (CO_ANO, NO_URF, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_urf_qtd        ON EXPORTACAO_RES (CO_ANO,SG_UF, NO_URF, QTD_REGISTROS)
CREATE INDEX idx_ano_via_qtd           ON EXPORTACAO_RES (CO_ANO, NO_VIA, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_via_qtd        ON EXPORTACAO_RES (CO_ANO,SG_UF, NO_VIA, QTD_REGISTROS)
CREATE INDEX idx_ano_vl_agregado       ON EXPORTACAO_RES (CO_ANO,VL_AGREGADO);
CREATE INDEX idx_ano_uf_vl_agregado    ON EXPORTACAO_RES (CO_ANO,SG_UF,VL_AGREGADO);
CREATE INDEX idx_ano_kg_liquido        ON EXPORTACAO_RES (CO_ANO,KG_LIQUIDO);
CREATE INDEX idx_ano_uf_kg_liquido     ON EXPORTACAO_RES (CO_ANO,SG_UF,KG_LIQUIDO);
CREATE INDEX idx_ano_vl_fob            ON EXPORTACAO_RES (CO_ANO,VL_FOB);
CREATE INDEX idx_ano_uf_vl_fob         ON EXPORTACAO_RES (CO_ANO,SG_UF,VL_FOB);


CREATE INDEX idx_no_sh4_por 	       ON IMPORTACAO_RES (NO_SH4_POR);
CREATE INDEX idx_no_sh6_por            ON IMPORTACAO_RES (NO_SH6_POR);
CREATE INDEX idx_ano_co_fat_qtd        ON IMPORTACAO_RES (CO_ANO, CO_FAT_AGREG, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_co_fat_qtd     ON IMPORTACAO_RES (CO_ANO, SG_UF, CO_FAT_AGREG, QTD_REGISTROS);
CREATE INDEX idx_ano_no_sh4_por_qtd    ON IMPORTACAO_RES (CO_ANO, NO_SH4_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_no_sh6_por_qtd    ON IMPORTACAO_RES (CO_ANO, NO_SH6_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_no_sh4_por_qtd ON IMPORTACAO_RES (CO_ANO, SG_UF, NO_SH4_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_no_sh6_por_qtd ON IMPORTACAO_RES (CO_ANO, SG_UF, NO_SH6_POR, QTD_REGISTROS);
CREATE INDEX idx_ano_urf_qtd 	       ON IMPORTACAO_RES (CO_ANO, NO_URF, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_urf_qtd        ON IMPORTACAO_RES (CO_ANO,SG_UF, NO_URF, QTD_REGISTROS)
CREATE INDEX idx_ano_via_qtd           ON IMPORTACAO_RES (CO_ANO, NO_VIA, QTD_REGISTROS);
CREATE INDEX idx_ano_uf_via_qtd        ON IMPORTACAO_RES (CO_ANO,SG_UF, NO_VIA, QTD_REGISTROS)
CREATE INDEX idx_ano_vl_agregado       ON IMPORTACAO_RES (CO_ANO,VL_AGREGADO);
CREATE INDEX idx_ano_uf_vl_agregado    ON IMPORTACAO_RES (CO_ANO,SG_UF,VL_AGREGADO);
CREATE INDEX idx_ano_kg_liquido        ON IMPORTACAO_RES (CO_ANO,KG_LIQUIDO);
CREATE INDEX idx_ano_uf_kg_liquido     ON IMPORTACAO_RES (CO_ANO,SG_UF,KG_LIQUIDO);
CREATE INDEX idx_ano_vl_total          ON IMPORTACAO_RES (CO_ANO,VL_TOTAL);
CREATE INDEX idx_ano_uf_vl_total       ON IMPORTACAO_RES (CO_ANO,SG_UF,VL_TOTAL);
